server:
  address: 127.0.0.2
  port: 80

spring:
  thymeleaf:
    cache: true
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: QianNvYouHun
    url: jdbc:mysql://localhost:3306/order_system?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis:
  type-aliases-package: pojo
  mapper-locations: classpath:mapper/*.xml